name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.md LICENSE *.gitignore *.git* .github/*'
    - uses: actions/upload-artifact@v1
      with:
        name: my-artifact
        path: ${{ github.workspace }}/result.zip
